# Generated by Django 3.0.5 on 2020-04-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0009_auto_20200415_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='category_type_id',
        ),
    ]
