# Generated by Django 3.0.5 on 2020-04-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0010_auto_20200415_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category_type_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
