# Generated by Django 3.0.5 on 2020-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0011_auto_20200415_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='קניות', max_length=150),
        ),
    ]
