# Generated by Django 3.0.5 on 2020-04-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0014_auto_20200415_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='limit',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
