# Generated by Django 3.0.5 on 2020-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0015_category_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
