# Generated by Django 3.0.5 on 2020-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0016_auto_20200415_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_expense',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
