# Generated by Django 3.0.5 on 2020-04-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0017_auto_20200415_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_expense',
        ),
    ]
