# Generated by Django 3.0.5 on 2020-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetta_app', '0018_remove_transaction_is_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
